# rustfmt configurations from master branch, check rustfmt version
# (cargo fmt --version).
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

edition = "2021"
fn_params_layout ="Compressed"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
tab_spaces = 4
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Off"
